version: '3.8'

services:
  movies:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev

# The volume is must for a development environment in order to \
#update the container whenever a change to the source code is made. 
#Without this, you would have to re-build the image each time you make a change to the code.